#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mono.Samples.HelloWorld.Resource", IsApplication=true)]

namespace Mono.Samples.HelloWorld
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.2.120")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int button1 = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int editText1 = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int editText2 = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int linearLayout1 = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int linearLayout2 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int textView1 = 2130837509;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int anmelden = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int usermenu = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int at1 = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int auftragsuchen = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int hello = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int login_text1 = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int user_text1 = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
