#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SimpleMapDemo.Resource", IsApplication=true)]

namespace SimpleMapDemo
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.2.120")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int monkey = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int polarbear = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int animateButton = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int description = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int listView = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int map = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int map_container = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int title = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int zoomInButton = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int zoomOutButton = 2130903047;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int BasicDemo = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Feature = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int MainActivity = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int MapLayout = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int MapWithOverlayLayout = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int MyLocationLayout = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int activity_description_axml = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int activity_description_mapwithmarkers = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int activity_description_mapwithoverlays = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int activity_description_mylocation = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int activity_label_axml = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int activity_label_mapwithmarkers = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int activity_label_mapwithoverlays = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int activity_label_mylocation = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int app_name = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int location_permission_missing = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int location_permission_rationale = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int mapsAppText = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int mapsAppTextDescription = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int ok = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int streetViewText = 2131034126;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
